config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :gift_cards, only: [:new, :create] do
    member do
      put :redeem
      put :invalidate
    end
  end

  resources :users, only: [:index] do
    member do
      put :make_pending
      put :make_regular
      put :make_admin
    end
    resources :api_keys, controller: 'users/api_keys', except: [:show]
  end

  root "gift_cards#index"

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :user
  validates_uniqueness_of :access_token

  before_create :set_access_token

  def self.not_expired
    where("expires_at > current_timestamp OR expires_at IS NULL")
  end

  private

  def set_access_token
    return if self.access_token.present?
    token = SecureRandom.hex
    while self.class.exists?(access_token: token) do
      token = SecureRandom.hex
    end
    self.access_token = token
  end

end

app/models/gift_card.rb
class GiftCard < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :user, :code, :value
  validates_uniqueness_of :code
  validates :value, numericality: { only_integer: true }, allow_blank: true

  after_initialize :set_initial_code
  before_validation :parameterize_code

  state_machine initial: :pending do

    state :pending
    state :redeemed
    state :invalid

    event :redeem do
      transition [:pending] => :redeemed
    end

    event :invalidate do
      transition [:pending] => :invalid
    end

  end

  def to_param
    self.code
  end

  private

  def set_initial_code
    self.code = "#{self.user.try(:id)}-#{Time.now.to_i.to_s(36)}-#{(rand * 100).to_i}" unless self.code.present?
  end

  def parameterize_code
    self.code = self.code.parameterize
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :gift_cards
  has_many :api_keys
  
  before_validation :extract_name_from_email

  state_machine initial: :pending do

    state :pending
    state :regular
    state :admin

    event :make_pending do
      transition [:regular, :admin] => :pending
    end

    event :make_regular do
      transition [:pending, :admin] => :regular
    end

    event :make_admin do
      transition [:pending, :regular] => :admin
    end

  end

  private

  def extract_name_from_email
    return unless self.email.present?
    self.name = self.email.match(/(.+)@/)[1] unless self.name.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_api!, if: -> { request.headers["HTTP_AUTHORIZATION"].present? }
  skip_before_filter :verify_authenticity_token, if: -> { request.headers["HTTP_AUTHORIZATION"].present? }
  after_action :verify_authorized, unless: -> {devise_controller?}
  after_action :verify_policy_scoped, only: %i[index], unless: -> {devise_controller?}
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  responders :flash, :location

  helper_method :namespace

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def user_not_authorized(exception)
    if request.headers["HTTP_AUTHORIZATION"].present?
      return render json: { error: t('unauthorized') }, status: :unauthorized
    else
      flash[:alert] = t('flash.not_authorized')
      redirect_to(request.referrer || root_path)
    end
  end

  def namespace
    names = self.class.to_s.split('::')
    return "null" if names.length < 2
    names[0..(names.length-2)].map(&:downcase).join('_')
  end

  def authenticate_api!
    authenticate_or_request_with_http_token do |token, options|
      api_key = ApiKey.not_expired.find_by_access_token(token)
      if api_key
        sign_in(:user, api_key.user)
      else
        return render json: { error: t('unauthorized') }, status: :unauthorized
      end
    end
  end

end

app/controllers/gift_cards_controller.rb
class GiftCardsController < StateController
  
  before_action :set_gift_card, except: %i[index new create]

  after_action :verify_authorized, except: %i[index]
  after_action :verify_policy_scoped, only: %i[index]

  respond_to :html, except: %i[redeem]
  respond_to :json, only: %i[redeem]

  def index
    @gift_cards = policy_scope(GiftCard)
    respond_with @gift_cards
  end

  def show
    authorize @gift_card
    respond_with @gift_card
  end

  def new
    @gift_card = GiftCard.new user: current_user
    authorize @gift_card
    respond_with @gift_card
  end

  def create
    @gift_card = GiftCard.new(gift_card_params)
    @gift_card.user = current_user
    authorize @gift_card
    @gift_card.save
    respond_with @gift_card, location: -> { root_path }
  end

  def edit
    authorize @gift_card
    respond_with @gift_card
  end

  def update
    authorize @gift_card
    @gift_card.update(gift_card_params)
    respond_with @gift_card
  end

  def destroy
    authorize @gift_card
    @gift_card.destroy
    respond_with @gift_card
  end

  def redeem
    authorize @gift_card
    return render json: { error: 'no_value', message: t('.no_value') }, status: 422 unless params[:value].present?
    return render json: { error: 'wrong_value', message: t('.wrong_value') }, status: 422 unless params[:value].to_i == @gift_card.value.to_i
    return render json: { error: 'cant_redeem', message: t('.cant_redeem') }, status: 422 unless @gift_card.can_redeem?
    transition_state(:redeem)
  end

  def invalidate
    transition_state(:invalidate)
  end

  private

  def gift_card_params
    params.require(:gift_card).permit(*policy(@gift_card || GiftCard.new).permitted_attributes)
  end

  def set_gift_card
    @gift_card = GiftCard.find_by_code!(params[:id])
  end

  def transition_state(transition)
    super(@gift_card, transition, root_path)
  end

end

app/controllers/state_controller.rb
class StateController < ApplicationController

  private

  def transition_state(resource, transition, redirect_path = nil)
    authorize resource
    resource_name = resource.class.model_name.human
    if resource.send("can_#{transition}?")
      resource.send("#{transition}!")
      flash[:notice] = t('flash.actions.update.notice', resource_name: resource_name)
    else
      flash[:alert] = t('flash.actions.update.alert', resource_name: resource_name)
    end
    respond_with resource, location: -> { redirect_path || resource }
  end

end

app/controllers/users/api_keys_controller.rb
class Users::ApiKeysController < ApplicationController

  before_action :set_user
  before_action :set_api_key, except: %i[index new create]

  respond_to :html

  after_action :verify_authorized, except: %i[index]
  after_action :verify_policy_scoped, only: %i[index]

  def index
    @api_keys = policy_scope(ApiKey).where(user: @user)
  end

  def new
    @api_key = @user.api_keys.new
    authorize @api_key
    respond_with @api_key
  end

  def create
    @api_key = @user.api_keys.new(api_key_params)
    authorize @api_key
    @api_key.save
    respond_with @api_key, location: -> { user_api_keys_path(@user) }
  end

  def edit
    authorize @api_key
    respond_with @api_key
  end

  def update
    authorize @api_key
    @api_key.update(api_key_params)
    respond_with @api_key, location: -> { user_api_keys_path(@user) }
  end

  def destroy
    authorize @api_key
    @api_key.destroy
    respond_with @api_key, location: -> { user_api_keys_path(@user) }
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_api_key
    @api_key = @user.api_keys.find(params[:id])
  end

  def api_key_params
    params.require(:api_key).permit(*policy(@api_key || ApiKey.new).permitted_attributes)
  end

end

app/controllers/users_controller.rb
class UsersController < StateController
  
  before_action :set_user, except: %i[index]

  respond_to :html

  def index
    @users = policy_scope(User)
    authorize User.new
    respond_with @users
  end

  def make_pending
    transition_state(:make_pending)
  end

  def make_regular
    transition_state(:make_regular)
  end

  def make_admin
    transition_state(:make_admin)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def transition_state(transition)
    super(@user, transition, users_path)
  end

end

app/views/gift_cards/_gift_card.html.slim
tr
  td= gift_card.user.name
  td= gift_card.code
  td= gift_card.value
  td= gift_card.human_state_name
  td
    ul class="button-group round"
      - if gift_card.can_invalidate?
        li= link_to t('activerecord.state_machines.gift_card.state.events.invalidate'), invalidate_gift_card_path(gift_card), method: :put, data: { confirm: t('confirm') }, class: 'button tiny'

app/views/gift_cards/index.html.slim
- content_for :title do
  = GiftCard.model_name.human.pluralize
- unless @gift_cards.nil? || @gift_cards.empty?
  table
    thead
      tr
        th= GiftCard.human_attribute_name(:user)
        th= GiftCard.human_attribute_name(:code)
        th= GiftCard.human_attribute_name(:value)
        th= GiftCard.human_attribute_name(:state)
        th
    tbody
      = render @gift_cards
- if policy(GiftCard.new).new?
  = link_to t('helpers.submit.create', model: GiftCard.model_name.human), new_gift_card_path, class: 'button'

app/views/gift_cards/new.html.slim
- content_for :title do
  = t('helpers.submit.create', model: GiftCard.model_name.human)
= simple_form_for @gift_card do |form|
  = form.input :code
  = form.input :value
  = form.button :submit

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="robots" content="index, follow"
    meta name="description" content=strip_tags(yield :title)
    meta name="author" content="Daniel Weinmann"
    title= "#{"#{strip_tags(yield :title)} · " if content_for?(:title)} Juntos Gift Cards"
    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tag
  body[data-namespace="#{namespace}" data-controller="#{controller_name}" data-action="#{action_name}" data-locale="#{I18n.locale}"]
    .fixed.contain-to-grid
      nav class="top-bar" data-topbar="true" role="navigation"
        ul class="title-area"
          li class="name"
            h1= link_to 'Juntos Gift Cards', root_path
          - if current_user
            li class="toggle-topbar menu-icon"
              a href="#"
                span
              section class="top-bar-section"
                ul class="right"
                  li class="has-dropdown"
                    a href="#"= current_user.name
                    ul class="dropdown"
                      - if policy(User.new).index?
                        li= link_to User.model_name.human.pluralize, users_path
                      li= link_to t('profile'), edit_user_registration_path
                      li= link_to t('logout'), destroy_user_session_path, method: :delete
    #content.row
      - if content_for?(:title)
        h1= yield :title
      - for key, msg in flash
        - unless key == :timedout
          - key = "success" if key == "notice"
          - key = "alert" if ["failure", "error"].include?(key)
          .alert-box class="#{key}" data-alert="true"
            = msg
            a href="#" class="close" &times
      = yield

app/views/users/_user.html.slim
tr
  td= user.name
  td= user.email
  td= user.human_state_name
  td
    ul class="button-group round"
      li= link_to ApiKey.model_name.human.pluralize, user_api_keys_path(user), class: 'button tiny'
      - if user.can_make_pending?
        li= link_to t('activerecord.state_machines.user.state.events.make_pending'), make_pending_user_path(user), method: :put, data: { confirm: t('confirm') }, class: 'button tiny'
      - if user.can_make_regular?
        li= link_to t('activerecord.state_machines.user.state.events.make_regular'), make_regular_user_path(user), method: :put, data: { confirm: t('confirm') }, class: 'button tiny'
      - if user.can_make_admin?
        li= link_to t('activerecord.state_machines.user.state.events.make_admin'), make_admin_user_path(user), method: :put, data: { confirm: t('confirm') }, class: 'button tiny'

app/views/users/api_keys/_api_key.html.slim
tr
  td= api_key.access_token
  td= l(api_key.expires_at) if api_key.expires_at
  td
    ul class="button-group round"
      li= link_to t('destroy'), user_api_key_path(@user, api_key), method: :delete, data: { confirm: t('confirm') }, class: "button tiny alert"

app/views/users/api_keys/index.html.slim
- content_for :title do
  = link_to @user.name, users_path
  = " » "
  = ApiKey.model_name.human.pluralize
- unless @api_keys.empty?
  table
    thead
      tr
        th= ApiKey.human_attribute_name(:access_token)
        th= ApiKey.human_attribute_name(:expires_at)
        th
    tbody
      = render @api_keys
- if policy(ApiKey.new).new?
  = link_to t('helpers.submit.create', model: ApiKey.model_name.human), new_user_api_key_path(@user), class: 'button'

app/views/users/api_keys/new.html.slim
- content_for :title do
  = link_to @user.name, users_path
  = " » "
  = t('helpers.submit.create', model: ApiKey.model_name.human)
= simple_form_for @api_key, url: user_api_keys_path(@user) do |form|
  = form.input :expires_at, as: :string
  = form.button :submit

app/views/users/index.html.slim
- content_for :title do
  = User.model_name.human.pluralize
table
  thead
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:state)
      th
  tbody
    = render @users